const REQUIRED_ENV_VARS = [
  'NODE_ENV',
  'PORT',
  'FRONTEND_URL',

  'DB_USER',
  'DB_PASSWORD',
  'DB_NAME',
  'DB_HOST',
  'DB_PORT',

  'SESSION_SECRET',

  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',

  'REDIS_URL',

  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SECRET',
  'STRIPE_PUBLISHABLE_KEY',

  'EMAIL_SERVICE_HOST',
  'EMAIL_SERVICE_PORT',
  'EMAIL_SERVICE_USER',
  'EMAIL_SERVICE_PASS',
];

module.exports = {
  REQUIRED_ENV_VARS,
};
